---
name: 'Terraform CI: fugaming.org'

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'fugaming.org/**'
  workflow_dispatch:
  pull_request:
    paths:
      - 'fugaming.org/**'

jobs:
  # terraform-check:
  #   uses: ./.github/workflows/terraform-check.yaml
  #   with:
  #     tf_version: 1.3.9
  #     working_directory: 'fugaming.org/'

  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      tf_version: 1.3.9
      working_directory: fugaming.org
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
