---
name: 'Terraform Apply: fugaming.org'

on:
  workflow_dispatch: {}

env:
  TERRAFORM_PLANFILE: terraform.tfplan

jobs:
  # terraform-check:
  #   uses: ./.github/workflows/terraform-check.yaml
  #   with:
  #     tf_version: 1.3.9
  #     working_directory: 

  terraform-plan:
    # needs: terraform-check
    uses: ./.github/workflows/terraform-plan.yaml
    with:
      tf_version: 1.3.9
      working_directory: fugaming.org
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-apply:
    needs: terraform-plan
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      tf_version: 1.3.9
      working_directory: fugaming.org
      aws_region: eu-west-2
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
